/**
 * Placeholder TypeScript type surface for the Api. This file is generated by
 * `npm run generate:api-types` against a running Api; the committed version here exists
 * so the Angular app can reference the DTOs during L10-2 before the Api is stood up for
 * the first time. It is overwritten verbatim by the codegen command.
 */

export interface UserMeResponse {
  userId: number;
  objectId: string;
  email: string;
  displayName: string | null;
  role: 'Member' | 'Admin';
  teamId: number;
  teamName: string;
}

export interface paths {
  '/api/users/me': {
    get: {
      responses: {
        200: { content: { 'application/json': UserMeResponse } };
        401: never;
        403: never;
      };
    };
  };
}
